[package]
name = "barebones-vcs"
version = "0.1.0"
edition = "2021"

[dependencies]
sha256 = "1.5.0"

strum = "0.26.3"
strum_macros = "0.26.3"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15.0"
